sudo: required

language: c++

services:
  - docker

install:
  - DEALII_TEST_DIR="/home/dealii/test"
  - docker pull dealii/dealii:latest

script:
  - docker run --rm -ti -v ${TRAVIS_BUILD_DIR}:${DEALII_TEST_DIR} dealii/dealii deps/run_test_in_docker.sh

