sudo: required

language: c++

services:
  - docker

install:
  - DEALII_TEST_DIR="/home/travis"
  - IMAGE="dealii/dealii:v9.2.0-focal"
  - docker pull ${IMAGE}

script:
  - docker run --rm -ti -v ${TRAVIS_BUILD_DIR}:${DEALII_TEST_DIR} ${IMAGE} ${DEALII_TEST_DIR}/run_test_in_docker.sh

