sudo: required

language: c++

addons:
  apt:
    sources: &sources
    - ubuntu-toolchain-r-test

    packages:
    - g++-5
    - gcc-5
    - g++-6
    - gcc-6


cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/dealii

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true
  
matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # LINUX
    # GCC 5
    - os: linux
      env: COMPILER=g++-5 CCOMPILER=gcc-5 COMPUTE_COVERAGE=false
      compiler: gcc

    # GCC 6
    - os: linux
      env: COMPILER=g++-6 CCOMPILER=gcc-6 GCOV=gcov-6 COMPUTE_COVERAGE=true MAKE_DOC=true
      compiler: gcc

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  ############################################################################
  # Override compiler if needed
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CC=${CCOMPILER}; fi

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
 
  ############################################################################
  # Install gtest
  ############################################################################
  - git clone https://github.com/google/googletest.git
  - cd googletest && mkdir build && cd build && cmake .. && make -j2
  - sudo cp -r ../googletest/include/gtest /usr/local/include/
  - sudo cp googlemock/gtest/lib*.a /usr/local/lib

  ############################################################################
  # Install FunG
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/lubkoll/FunG.git
  - sudo cp -r FunG/fung /usr/local/include

  ############################################################################
  # Install dealII
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/dealii/dealii.git
  - cd dealii && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DDEAL_II_COMPONENT_EXAMPLES=OFF
  - sudo make -j2 install

  ############################################################################
  # Install Spacy
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/spacy-dev/Spacy.git
  - cd Spacy && mkdir build && cd build && cmake .. -DdealII=ON -DCMAKE_BUILD_TYPE=Release && make -j2 && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DdealII=ON -DCMAKE_BUILD_TYPE=Release
  - make -j2 && ctest

